# -----------------------------------------------------------------------
# flyway.toml
# Configuración común a todos los entornos - Oracle Database
# -----------------------------------------------------------------------

locations = [
  "filesystem:./tables",
  "filesystem:./views", 
  "filesystem:./procedures",
  "filesystem:./functions"
]

# Conexión y credenciales Oracle (genéricas; se pueden sobreescribir en entornos)
url                   = "jdbc:oracle:thin:@68.233.125.70/dev_db"
user                  = "${FLYWAY_ORACLE_USER}"
password              = "${FLYWAY_ORACLE_PASSWORD}"
driver                = "oracle.jdbc.OracleDriver"
schemas               = ["DEV_ADMIN"]
defaultSchema         = "DEV_ADMIN"

# Convenciones de nombres
sqlMigrationPrefix      = "V"
undoSqlMigrationPrefix = "U"
sqlMigrationSeparator   = "__"
sqlMigrationSuffixes    = [".sql"]

# Configuraciones específicas para Oracle
placeholderReplacement = true

# Oracle-specific settings
oracle.sqlplus         = false

# Validaciones y Enterprise features
undoEnabled           = true
validateOnMigrate     = true
cleanDisabled         = true
allowMixedMigrations  = false
driftReport           = true
driftReportFormat     = "html"
repairOnValidationError = true

# Configuración de transacciones para Oracle
group                 = false
mixed                 = false

# Salida de logs
outputFile            = "flyway-output.log"
teamcity              = false

# -----------------------------------------------------------------------
# Entornos específicos
# -----------------------------------------------------------------------

[environments.development]
url       = "jdbc:oracle:thin:@68.233.125.70:1521/main_db"
user      = "main_db"
password  = "MainAdmin123"
schemas   = ["main_db"]
defaultSchema = "main_db"
[environments.development.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]

# Configuración para producción (ajustar según tus datos de producción)
[environments.production]
url      = "jdbc:oracle:thin:@68.233.125.70:1521/dev_db"
user     = "dev_admin"
password = "DevAdmin123"
schemas  = ["DEV_SCHEMA"]
defaultSchema = "DEV_SCHEMA"
[environments.production.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]