# -----------------------------------------------------------------------
# flyway.toml
# Configuración común a todos los entornos - Oracle Database
# -----------------------------------------------------------------------

locations = [
  "filesystem:./tables",
  "filesystem:./views", 
  "filesystem:./procedures",
  "filesystem:./functions"
]

# Conexión y credenciales Oracle (genéricas; se pueden sobreescribir en entornos)
url                   = "jdbc:oracle:thin:@68.233.125.70/dev_db"
user                  = "${FLYWAY_ORACLE_USER}"
password              = "${FLYWAY_ORACLE_PASSWORD}"
driver                = "oracle.jdbc.OracleDriver"
schemas               = ["DEV_ADMIN"]
defaultSchema         = "DEV_ADMIN"

# Convenciones de nombres
sqlMigrationPrefix      = "V"
undoSqlMigrationPrefix = "U"
sqlMigrationSeparator   = "__"
sqlMigrationSuffixes    = [".sql"]

# Configuraciones específicas para Oracle
placeholderReplacement = true

# Oracle-specific settings
oracle.sqlplus         = false

# Validaciones y Enterprise features
[check]
enabled = true
drift = true
buildEnvironment = "development"
deployedSnapshot = "snapshots/data-baseline.sql"
reportEnabled = true
reportFilename = "./reports/drift-report.html"
reportFormat = "html"
reportOpen = true
changeReportEnabled = true
changeReportFilename = "./reports/change-report.html"
migrationReportEnabled = true
migrationReportFilename = "./reports/migration-report.html"
dryRunReportEnabled = true
dryRunReportFilename = "./reports/dry-run-report.html"


# Configuración de transacciones para Oracle
group                 = false
mixed                 = false

# Salida de logs
outputFile            = "flyway-output.log"
teamcity              = false

[snapshot]
filename = "./snapshots/data-baseline.sql"

# -----------------------------------------------------------------------
# Entornos específicos
# -----------------------------------------------------------------------

[environments.development]
url       = "jdbc:oracle:thin:@68.233.125.70:1521/main_db"
user      = "main_db"
password  = "MainAdmin123"
schemas   = ["MAIN_ADMIN"]
defaultSchema = "MAIN_ADMIN"
[environments.development.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]
cleanDisabled = false
[environments.development.snapshot]
filename = "./snapshots/main-baseline.sql"


# Configuración para producción (ajustar según tus datos de producción)
[environments.production]
url      = "jdbc:oracle:thin:@68.233.125.70:1521/dev_db"
user     = "dev_admin"
password = "DevAdmin123"
schemas  = ["DEV_SCHEMA"]
defaultSchema = "DEV_SCHEMA"
[environments.production.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]
cleanDisabled = false
[environments.production.snapshot]
filename = "./snapshots/main-baseline.sql"