# -----------------------------------------------------------------------
# flyway.toml
# Configuración común a todos los entornos
# -----------------------------------------------------------------------


locations = [
  "filesystem:tables",
  "filesystem:views", 
  "filesystem:procedures",
  "filesystem:functions"
]

# Conexión y credenciales (genéricas; se pueden sobreescribir en entornos)
url                   = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=DEV_db;encrypt=true;trustServerCertificate=true"
user                  = "${FLYWAY_SQLSERVER_USER}"
password              = "${FLYWAY_SQLSERVER_PASSWORD}"
driver                = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
schemas               = ["dbo"]
defaultSchema         = "dbo"

# Convenciones de nombres
sqlMigrationPrefix      = "V"
undoSqlMigrationPrefix = "U"
sqlMigrationSeparator   = "__"
sqlMigrationSuffixes    = [".sql"]

# Validaciones y Enterprise features
undoEnabled           = true
validateOnMigrate     = true
cleanDisabled         = true
allowMixedMigrations  = false
driftReport           = true
driftReportFormat     = "html"
repairOnValidationError = true

# Salida de logs
outputFile            = "flyway-output.log"
teamcity              = false

# -----------------------------------------------------------------------
# Entornos específicos
# -----------------------------------------------------------------------

[environments.development]
url       = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=DEV_db;encrypt=true;trustServerCertificate=true"
user      = "dev_user"
password  = "Dev123456789!"
schemas   = ["dbo"]
[environments.development.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures"]


[environments.production]
url      = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=QA_db;encrypt=true;trustServerCertificate=true"
user     = "${FLYWAY_SQLSERVER_USER}"
password = "${FLYWAY_SQLSERVER_PASSWORD}"
schemas  = ["dbo"]
[environments.production.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures"]
# text