# -----------------------------------------------------------------------
# Flyway config para SQL Server (Dev environment)
# Ubicación del archivo:
# repo-root/dev/Server/SQLServer/Demo-TEXT/MyDatabase/flyway.toml
# -----------------------------------------------------------------------


locations = [
  "filesystem:./tables",
  "filesystem:./views", 
  "filesystem:./procedures",
  "filesystem:./functions"
]

# Prefijos y sufijos de archivos
flyway.sqlMigrationPrefix = "V"
flyway.undoSqlMigrationPrefix = "U"
flyway.sqlMigrationSeparator = "__"
flyway.sqlMigrationSuffixes = [".sql"]

# Esquema de metadatos (puede ser distinto del esquema de objetos)
flyway.schemas = ["dbo"]

# Enterprise features
# Generar reporte HTML de drift cada vez que se ejecute flyway drift
flyway.driftReport = true
flyway.driftReportFormat = "html"

# Habilitar undo (solo si existen scripts U*)
flyway.undoEnabled = true

# Salida de logs
outputFile            = "flyway-output.log"
teamcity              = false

# -----------------------------------------------------------------------
# Entornos específicos
# -----------------------------------------------------------------------

[environments.development]
url       = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=MAIN_db;encrypt=true;trustServerCertificate=true"
user      = "dev_user"
password  = "Dev123456789!"
schemas   = ["dbo"]
[environments.development.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]


[environments.production]
url      = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=DEV_db;integratedSecurity=true;encrypt=true;trustServerCertificate=true"
schemas  = ["dbo"]
[environments.production.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures","filesystem:./functions"]

