# -----------------------------------------------------------------------
# Flyway config para SQL Server (Dev environment)
# Ubicación del archivo:
# repo-root/dev/Server/SQLServer/Demo-TEXT/MyDatabase/flyway.toml
# -----------------------------------------------------------------------

# Conexión JDBC
flyway.url = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=MyDatabase"

# Credenciales (mejor guardarlas en Jenkins Credentials y referenciarlas aquí)
flyway.user = "${FLYWAY_SQLSERVER_USER}"
flyway.password = "${FLYWAY_SQLSERVER_PASSWORD}"

# Ubicaciones de los scripts (relativas al directorio de flyway.toml)
flyway.locations = [
  "filesystem:tables",
  "filesystem:views",
  "filesystem:procedures",
  "filesystem:functions"
]

# Prefijos y sufijos de archivos
flyway.sqlMigrationPrefix = "V"
flyway.undoSqlMigrationPrefix = "U"
flyway.sqlMigrationSeparator = "__"
flyway.sqlMigrationSuffixes = [".sql"]

# Esquema de metadatos (puede ser distinto del esquema de objetos)
flyway.schemas = ["dbo"]

# Enterprise features
# Generar reporte HTML de drift cada vez que se ejecute flyway drift
flyway.driftReport = true
flyway.driftReportFormat = "html"

# Habilitar undo (solo si existen scripts U*)
flyway.undoEnabled = true

# Validación de checksum antes de migrar
flyway.validateOnMigrate = true

# Permitir reparar automáticamente los metadatos si cambia un checksum
flyway.cleanDisabled = true
flyway.allowMixedMigrations = false
flyway.repairOnValidationError = true

# Directivas de logging/output (útil para archivar logs en Jenkins)
flyway.outputFile = "flyway-output.log"
flyway.teamcity = false
