# -----------------------------------------------------------------------
# flyway.toml
# Configuración común a todos los entornos
# -----------------------------------------------------------------------


locations = [
  "filesystem:./tables",
  "filesystem:./views", 
  "filesystem:./procedures",
  "filesystem:./functions"
]

# Conexión y credenciales (genéricas; se pueden sobreescribir en entornos)
url                   = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=DEV_db;encrypt=true;trustServerCertificate=true"
user                  = "${FLYWAY_SQLSERVER_USER}"
password              = "${FLYWAY_SQLSERVER_PASSWORD}"
driver                = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
schemas               = ["dbo"]
defaultSchema         = "dbo"

# Convenciones de nombres
sqlMigrationPrefix      = "V"
undoSqlMigrationPrefix = "U"
sqlMigrationSeparator   = "__"
sqlMigrationSuffixes    = [".sql"]

# Validaciones y Enterprise features
undoEnabled           = true
validateOnMigrate     = true
cleanDisabled         = true
allowMixedMigrations  = false
driftReport           = true
repairOnValidationError = true

# Salida de logs
outputFile            = "flyway-output.log"
teamcity              = false

[check]
enabled = true
drift = true
buildEnvironment = "development"
deployedSnapshot = "./snapshots/main-baseline.sql"
reportEnabled = true
reportFilename = "./reports/drift-report.html"
reportFormat = "html"
reportOpen = true
changeReportEnabled = true
changeReportFilename = "./reports/change-report.html"
migrationReportEnabled = true
migrationReportFilename = "./reports/migration-report.html"
dryRunReportEnabled = true
dryRunReportFilename = "./reports/dry-run-report.html"

# -----------------------------------------------------------------------
# Entornos específicos
# -----------------------------------------------------------------------

[environments.development]
url       = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=MAIN_db;encrypt=true;trustServerCertificate=true"
user      = "dev_user"
password  = "Dev123456789!"
schemas   = ["dbo"]
[environments.development.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures", "filesystem:./functions"]
cleanDisabled = false
[environments.development.snapshot]
filename = "./snapshots/main-baseline.sql"


 

[environments.production]
url      = "jdbc:sqlserver://DEMO-FLYWAY:1433;databaseName=DEV_db;integratedSecurity=true;encrypt=true;trustServerCertificate=true"
schemas  = ["dbo"]
[environments.production.flyway]
locations = ["filesystem:./tables", "filesystem:./views", "filesystem:./procedures","filesystem:./functions"]
cleanDisabled = false
[environments.production.snapshot]
filename = "./snapshots/dev-baseline.sql"
[environments.development.check]
enabled = true
drift = true
buildEnvironment = "production"
deployedSnapshot = "./snapshots/dev-baseline.sql"
reportEnabled = true
reportFilename = "./reports/drift-report-dev.html"
reportFormat = "html"
reportOpen = true
changeReportEnabled = true
changeReportFilename = "./reports/change-report-dev.html"
migrationReportEnabled = true
migrationReportFilename = "./reports/migration-report-dev.html"
dryRunReportEnabled = true
dryRunReportFilename = "./reports/dry-run-report-dev.html"